-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS v1.admins
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    account_verified boolean NOT NULL DEFAULT false,
    CONSTRAINT admins_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS v1.course_rating
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    rating integer NOT NULL,
    course_id integer NOT NULL,
    CONSTRAINT course_reting_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS v1.course_sections
(
    id serial NOT NULL,
    title character varying(50) COLLATE pg_catalog."default" NOT NULL,
    course_id integer NOT NULL,
    content character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    description character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT course_sections_pkey PRIMARY KEY (id),
    CONSTRAINT section_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS v1.courses
(
    id serial NOT NULL,
    title character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description character varying(150) COLLATE pg_catalog."default" NOT NULL,
    tags character varying(100) COLLATE pg_catalog."default" NOT NULL,
    picture_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_premium boolean NOT NULL,
    owner_id integer NOT NULL,
    is_hidden boolean NOT NULL DEFAULT false,
    average_rating real NOT NULL DEFAULT 0,
    rating_count integer NOT NULL DEFAULT 0,
    created_on timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT courses_key PRIMARY KEY (id),
    CONSTRAINT course_title_key UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS v1.enrollments
(
    id serial NOT NULL,
    student_id integer NOT NULL,
    course_id integer NOT NULL,
    is_approved boolean NOT NULL DEFAULT false,
    requested_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at timestamp with time zone,
    completed_at timestamp with time zone,
    CONSTRAINT enrollments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS v1.event_log
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    description character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "timestamp" time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    event_type character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS v1.external_resources
(
    id serial NOT NULL,
    course_section_id integer NOT NULL,
    url character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT external_resources_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS v1.section_progress
(
    id serial NOT NULL,
    student_id integer NOT NULL,
    section_id integer NOT NULL,
    is_completed boolean NOT NULL DEFAULT false,
    course_id integer NOT NULL,
    CONSTRAINT section_progress_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS v1.students
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT students_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS v1.subscriptions
(
    id serial NOT NULL,
    student_id integer NOT NULL,
    subscribed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expire_date date NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT subscriptions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS v1.teachers
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    mobile character varying(10) COLLATE pg_catalog."default" NOT NULL,
    linked_in_url character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email_verified boolean NOT NULL DEFAULT false,
    CONSTRAINT teachers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS v1.users
(
    id serial NOT NULL,
    role character varying(10) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    avatar_url character varying(255) COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT false,
    notifications boolean NOT NULL DEFAULT true,
    created_on timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS v1.admins
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES v1.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS v1.course_rating
    ADD CONSTRAINT course_id FOREIGN KEY (course_id)
    REFERENCES v1.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS v1.course_rating
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES v1.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS v1.course_sections
    ADD CONSTRAINT course_id FOREIGN KEY (course_id)
    REFERENCES v1.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS v1.courses
    ADD CONSTRAINT owner_id FOREIGN KEY (owner_id)
    REFERENCES v1.teachers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS v1.enrollments
    ADD CONSTRAINT course_id FOREIGN KEY (course_id)
    REFERENCES v1.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS v1.enrollments
    ADD CONSTRAINT student_id FOREIGN KEY (student_id)
    REFERENCES v1.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS v1.event_log
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES v1.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS v1.external_resources
    ADD CONSTRAINT course_section_id FOREIGN KEY (course_section_id)
    REFERENCES v1.course_sections (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS v1.section_progress
    ADD CONSTRAINT course_id FOREIGN KEY (course_id)
    REFERENCES v1.courses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS v1.section_progress
    ADD CONSTRAINT section_id FOREIGN KEY (section_id)
    REFERENCES v1.course_sections (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS v1.section_progress
    ADD CONSTRAINT student_id FOREIGN KEY (student_id)
    REFERENCES v1.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS v1.students
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES v1.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS v1.subscriptions
    ADD CONSTRAINT student_id FOREIGN KEY (student_id)
    REFERENCES v1.students (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS v1.teachers
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES v1.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;